name: Build for Android and Apple

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Используем актуальную версию checkout

    - name: Set up Python
      uses: actions/setup-python@v4  # Используем актуальную версию setup-python
      with:
        python-version: '3.8'  # Укажите версию Python, которую вы используете

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Если у вас есть файл requirements.txt

    - name: Build for Android
      run: |
        python3 build/main.py android

    - name: Build for Apple (gomobile)
      run: |
        python3 build/main.py apple gomobile



    - name: Notify build status
      if: always()
      run: |
        echo "Build status: ${{ job.status }}"
